import { useEffect, useMemo, useRef, useState } from 'react';
import {
  Avatar,
  Badge,
  Button,
  Checkbox,
  Dropdown,
  Empty,
  Input,
  List,
  Modal,
  Popconfirm,
  Select,
  Space,
  Tag,
  Tooltip,
  Typography,
  message,
} from 'antd';
import {
  BellOutlined,
  CheckCircleOutlined,
  CheckOutlined,
  CloseOutlined,
  DeleteOutlined,
  FileOutlined,
  FolderOutlined,
  FolderOpenOutlined,
  MessageOutlined,
  PaperClipOutlined,
  PlusOutlined,
  ReloadOutlined,
  RobotOutlined,
  SearchOutlined,
  SendOutlined,
  ShareAltOutlined,
  SnippetsOutlined,
  UserDeleteOutlined,
} from '@ant-design/icons';
import { useProjectStore } from '../../stores/projectStore';
import { useProjectDocStore } from '../../stores/projectDocStore';
import { useTemplateStore } from '../../stores/templateStore';
import { useAIJobStore } from '../../stores/aiJobStore';
import { useTaskStore } from '../../stores/taskStore';
import type { AIJob, ProjectDocument, ReviewResult } from '../../../shared/types';

const { Text } = Typography;

type NotificationTarget = 'overview' | 'project-plan' | 'project-report' | 'project-review';
type ConversationKey = 'system' | 'ai' | 'notes' | `friend:${string}`;

type SystemMessage = {
  id: string;
  category: '报告' | '审查' | '截止' | '便签';
  severity: 'high' | 'medium' | 'low';
  title: string;
  content: string;
  createdAt: string;
  target: NotificationTarget;
  projectId?: string;
  noteId?: string;
};

type LocalReply = { id: string; messageId: string; content: string; createdAt: string };
type MessageNote = {
  id: string;
  title: string;
  content: string;
  createdAt: string;
  updatedAt: string;
  dueAt?: string;
  completed?: boolean;
  sourceMessageId?: string;
  notified?: Array<'due-soon' | 'overdue'>;
};
type MessageKind = 'system' | 'ai' | 'friend';
type MessageReference = {
  id: string;
  kind: MessageKind;
  title: string;
  content: string;
  createdAt: string;
  system?: SystemMessage;
  aiJob?: AIJob;
  chat?: CollaborationChatMessage;
};

const DISMISSED_KEY = 'projecthub.message-center.dismissed.v1';
const REPLIES_KEY = 'projecthub.message-center.replies.v1';
const READ_KEY = 'projecthub.message-center.read.v1';
const HIDDEN_CHAT_KEY = 'projecthub.message-center.hidden-chat.v1';
const NOTES_KEY = 'projecthub.message-center.notes.v1';
const NOTE_DUE_SOON_MS = 24 * 60 * 60 * 1000;

const safeDateMs = (value?: string) => {
  const ms = value ? new Date(value).getTime() : 0;
  return Number.isFinite(ms) ? ms : 0;
};

const formatTime = (value: string) => {
  const date = new Date(value);
  if (!Number.isFinite(date.getTime())) return '';
  return `${date.getMonth() + 1}/${date.getDate()} ${String(date.getHours()).padStart(2, '0')}:${String(date.getMinutes()).padStart(2, '0')}`;
};

const loadLocal = <T,>(key: string, fallback: T): T => {
  try {
    const raw = localStorage.getItem(key);
    return raw ? JSON.parse(raw) as T : fallback;
  } catch {
    return fallback;
  }
};

const saveLocal = (key: string, value: unknown) => {
  try { localStorage.setItem(key, JSON.stringify(value)); } catch {}
};

const InteractiveMessage = ({
  children,
  menuItems,
  onClick,
}: {
  children: React.ReactElement;
  menuItems: NonNullable<React.ComponentProps<typeof Dropdown>['menu']>['items'];
  onClick?: () => void;
}) => {
  const [open, setOpen] = useState(false);
  const timerRef = useRef<number | null>(null);
  const unlockTimerRef = useRef<number | null>(null);
  const suppressClickRef = useRef(false);
  const holdOpenRef = useRef(false);
  const clearTimer = () => {
    if (timerRef.current !== null) window.clearTimeout(timerRef.current);
    timerRef.current = null;
  };
  const releaseOpenLock = () => {
    if (!holdOpenRef.current) return;
    if (unlockTimerRef.current !== null) window.clearTimeout(unlockTimerRef.current);
    // The pointer-up/click generated by the same long press must not be
    // interpreted by rc-trigger as an outside click.
    unlockTimerRef.current = window.setTimeout(() => {
      holdOpenRef.current = false;
      unlockTimerRef.current = null;
    }, 220);
  };
  useEffect(() => () => {
    clearTimer();
    if (unlockTimerRef.current !== null) window.clearTimeout(unlockTimerRef.current);
  }, []);
  return (
    <Dropdown
      menu={{ items: menuItems }}
      trigger={['contextMenu']}
      open={open}
      onOpenChange={nextOpen => {
        if (!nextOpen && holdOpenRef.current) return;
        setOpen(nextOpen);
      }}
    >
      <div
        className="message-interactive-wrap"
        onPointerDown={event => {
          if (event.button !== 0) return;
          clearTimer();
          timerRef.current = window.setTimeout(() => {
            suppressClickRef.current = true;
            holdOpenRef.current = true;
            setOpen(true);
          }, 560);
        }}
        onPointerUp={() => {
          clearTimer();
          releaseOpenLock();
        }}
        onPointerCancel={() => {
          clearTimer();
          releaseOpenLock();
        }}
        onPointerLeave={() => {
          clearTimer();
          releaseOpenLock();
        }}
        onContextMenu={event => {
          event.preventDefault();
          clearTimer();
          holdOpenRef.current = false;
          setOpen(true);
        }}
        onClick={() => {
          if (suppressClickRef.current) {
            suppressClickRef.current = false;
            return;
          }
          onClick?.();
        }}
      >
        {children}
      </div>
    </Dropdown>
  );
};

const buildNoteMessages = (notes: MessageNote[]): SystemMessage[] => {
  const now = Date.now();
  return notes.flatMap(note => {
    if (note.completed || !note.dueAt) return [];
    const due = safeDateMs(note.dueAt);
    if (!due || due - now > NOTE_DUE_SOON_MS) return [];
    const overdue = due <= now;
    return [{
      id: `note:${overdue ? 'overdue' : 'due-soon'}:${note.id}:${note.dueAt}`,
      category: '便签' as const,
      severity: overdue ? 'high' as const : 'medium' as const,
      title: overdue ? `便签已逾期 · ${note.title}` : `便签即将到期 · ${note.title}`,
      content: note.content || (overdue ? '该便签已超过设定时限。' : '该便签将在 24 小时内到期。'),
      createdAt: note.dueAt,
      target: 'overview' as const,
      noteId: note.id,
    }];
  });
};

const buildSystemMessages = (projects: { id: string; name: string }[], docs: ProjectDocument[], reviews: ReviewResult[]): SystemMessage[] => {
  const now = Date.now();
  const entries: SystemMessage[] = [];
  for (const project of projects) {
    const reportDocs = docs
      .filter(doc => doc.projectId === project.id && Boolean(doc.aiReport))
      .sort((a, b) => safeDateMs(b.analyzedAt || b.createdAt) - safeDateMs(a.analyzedAt || a.createdAt));
    if (reportDocs[0]) {
      const latest = reportDocs[0];
      entries.push({
        id: `report:${project.id}:${latest.id}:${latest.analyzedAt || latest.createdAt}`,
        category: '报告', severity: 'low', title: `报告已生成 · ${project.name}`,
        content: reportDocs.length > 1 ? `已生成或更新 ${reportDocs.length} 份报告，最新为《${latest.name}》。` : `《${latest.name}》已生成，可进入报告工作台查看。`,
        createdAt: latest.analyzedAt || latest.createdAt, target: 'project-report', projectId: project.id,
      });
    }

    const latestReview = reviews
      .filter(review => review.projectId === project.id)
      .sort((a, b) => safeDateMs(b.createdAt) - safeDateMs(a.createdAt))[0];
    if (latestReview) {
      const issueCount = latestReview.issues?.length || 0;
      const errorCount = latestReview.issues?.filter(issue => issue.severity === 'error').length || 0;
      entries.push({
        id: `review:${project.id}:${latestReview.id}`,
        category: '审查', severity: errorCount || latestReview.score < 60 ? 'high' : issueCount || latestReview.score < 80 ? 'medium' : 'low',
        title: `审查已完成 · ${project.name}`,
        content: `本次得分 ${latestReview.score} 分，发现 ${issueCount} 个问题${errorCount ? `，其中 ${errorCount} 个需要优先处理` : ''}。`,
        createdAt: latestReview.createdAt, target: 'project-review', projectId: project.id,
      });
    }

    const deadlines = docs
      .filter(doc => doc.projectId === project.id && doc.deadline && !doc.completedAt)
      .map(doc => ({ doc, deadline: safeDateMs(doc.deadline) }))
      .filter(item => item.deadline && item.deadline - now <= 3 * 24 * 60 * 60 * 1000)
      .sort((a, b) => a.deadline - b.deadline);
    if (deadlines[0]) {
      const overdue = deadlines.filter(item => item.deadline < now).length;
      entries.push({
        id: `deadline:${project.id}:${deadlines[0].doc.id}:${deadlines[0].doc.deadline}`,
        category: '截止', severity: overdue ? 'high' : 'medium', title: overdue ? `有逾期事项 · ${project.name}` : `临近截止 · ${project.name}`,
        content: overdue ? `${overdue} 个阶段已逾期，请优先安排处理。` : `共有 ${deadlines.length} 个阶段临近截止，最近截止时间为 ${formatTime(deadlines[0].doc.deadline || '')}。`,
        createdAt: new Date(Math.max(now, deadlines[0].deadline)).toISOString(), target: 'project-plan', projectId: project.id,
      });
    }
  }
  return entries.sort((a, b) => safeDateMs(b.createdAt) - safeDateMs(a.createdAt));
};

const aiStatusMeta: Record<AIJob['status'], { label: string; color: string }> = {
  queued: { label: '排队中', color: 'default' },
  running: { label: '进行中', color: 'processing' },
  completed: { label: '已完成', color: 'success' },
  failed: { label: '失败', color: 'error' },
  cancelled: { label: '已取消', color: 'default' },
};

interface FriendChatWorkspaceProps {
  open: boolean;
  friends: CollaborationPeerInfo[];
  selectedFriend: CollaborationPeerInfo | null;
  messages: CollaborationChatMessage[];
  loadingMessages: boolean;
  draft: string;
  sending: boolean;
  sendingFile: boolean;
  pendingRequestCount: number;
  onClose: () => void;
  onSelectFriend: (friend: CollaborationPeerInfo) => void;
  onDraftChange: (value: string) => void;
  onSendMessage: () => void;
  onSendFile: () => void;
  onSendFolder: () => void;
  onShareProject: () => void;
  onOpenAddFriend: () => void;
  onRefresh: () => void;
  onRemoveFriend: (friendId: string) => void;
  onOpenSystemTarget: (target: NotificationTarget, projectId?: string) => void;
}

const FriendChatWorkspace = ({
  open, friends, selectedFriend, messages, loadingMessages, draft, sending, sendingFile, pendingRequestCount,
  onClose, onSelectFriend, onDraftChange, onSendMessage, onSendFile, onSendFolder, onShareProject,
  onOpenAddFriend, onRefresh, onRemoveFriend, onOpenSystemTarget,
}: FriendChatWorkspaceProps) => {
  const projects = useProjectStore(state => state.projects);
  const currentProjectId = useProjectStore(state => state.currentProject?.id);
  const projectDocs = useProjectDocStore(state => state.projectDocs);
  const reviews = useTemplateStore(state => state.reviews);
  const { jobs: aiJobs, cancelJob, retryJob, clearJob } = useAIJobStore();
  const loadTasks = useTaskStore(state => state.loadTasks);
  const [keyword, setKeyword] = useState('');
  const [activeKey, setActiveKey] = useState<ConversationKey>('system');
  const [acceptingTaskOfferId, setAcceptingTaskOfferId] = useState('');
  const [acceptProjectId, setAcceptProjectId] = useState('');
  const [respondingTaskOffer, setRespondingTaskOffer] = useState(false);
  const [dismissedIds, setDismissedIds] = useState<string[]>(() => loadLocal<string[]>(DISMISSED_KEY, []));
  const [replies, setReplies] = useState<LocalReply[]>(() => loadLocal<LocalReply[]>(REPLIES_KEY, []));
  const [readIds, setReadIds] = useState<string[]>(() => loadLocal<string[]>(READ_KEY, []));
  const [hiddenChatIds, setHiddenChatIds] = useState<string[]>(() => loadLocal<string[]>(HIDDEN_CHAT_KEY, []));
  const [notes, setNotes] = useState<MessageNote[]>(() => loadLocal<MessageNote[]>(NOTES_KEY, []));
  const [systemDraft, setSystemDraft] = useState('');
  const [selectionMode, setSelectionMode] = useState(false);
  const [selectedMessageIds, setSelectedMessageIds] = useState<Set<string>>(new Set());
  const [forwardItems, setForwardItems] = useState<MessageReference[]>([]);
  const [forwardFriendIds, setForwardFriendIds] = useState<string[]>([]);
  const [forwarding, setForwarding] = useState(false);
  const [noteEditorOpen, setNoteEditorOpen] = useState(false);
  const [editingNoteId, setEditingNoteId] = useState('');
  const [noteTitle, setNoteTitle] = useState('');
  const [noteContent, setNoteContent] = useState('');
  const [noteDueAt, setNoteDueAt] = useState('');
  const [noteSourceMessageId, setNoteSourceMessageId] = useState('');
  const [messageStateLoaded, setMessageStateLoaded] = useState(false);
  const messageEndRef = useRef<HTMLDivElement>(null);

  const persistMessageCenterState = (overrides: Partial<{
    dismissedIds: string[];
    replies: LocalReply[];
    readIds: string[];
    hiddenChatIds: string[];
    notes: MessageNote[];
  }> = {}) => {
    const state = { dismissedIds, replies, readIds, hiddenChatIds, notes, ...overrides };
    saveLocal(DISMISSED_KEY, state.dismissedIds);
    saveLocal(REPLIES_KEY, state.replies);
    saveLocal(READ_KEY, state.readIds);
    saveLocal(HIDDEN_CHAT_KEY, state.hiddenChatIds);
    saveLocal(NOTES_KEY, state.notes);
    void window.electronAPI.saveMessageCenterState?.(state);
  };

  useEffect(() => {
    let cancelled = false;
    const request = window.electronAPI.loadMessageCenterState?.();
    if (!request) {
      setMessageStateLoaded(true);
      persistMessageCenterState();
      return () => { cancelled = true; };
    }
    void request.then(result => {
      if (cancelled || !result?.success) return;
      if (result.state) {
        const nextDismissedIds = Array.isArray(result.state.dismissedIds) ? result.state.dismissedIds : [];
        const nextReplies = Array.isArray(result.state.replies) ? result.state.replies as LocalReply[] : [];
        const nextReadIds = Array.isArray(result.state.readIds) ? result.state.readIds : [];
        const nextHiddenChatIds = Array.isArray(result.state.hiddenChatIds) ? result.state.hiddenChatIds : [];
        const nextNotes = Array.isArray(result.state.notes) ? result.state.notes as MessageNote[] : [];
        setDismissedIds(nextDismissedIds);
        setReplies(nextReplies);
        setReadIds(nextReadIds);
        setHiddenChatIds(nextHiddenChatIds);
        setNotes(nextNotes);
      } else {
        persistMessageCenterState();
      }
    }).catch(() => {}).finally(() => {
      if (!cancelled) setMessageStateLoaded(true);
    });
    return () => { cancelled = true; };
  // Read once per workspace-mounted message center. The main process owns the
  // workspace path, while localStorage is only a migration fallback.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const systemMessages = useMemo(
    () => [...buildNoteMessages(notes), ...buildSystemMessages(projects, projectDocs, reviews)]
      .filter(item => !dismissedIds.includes(item.id))
      .sort((a, b) => safeDateMs(b.createdAt) - safeDateMs(a.createdAt)),
    [dismissedIds, notes, projectDocs, projects, reviews],
  );
  const unreadSystemMessages = useMemo(() => systemMessages.filter(item => !readIds.includes(item.id)), [readIds, systemMessages]);
  const visibleFriends = useMemo(() => {
    const query = keyword.trim().toLocaleLowerCase();
    if (!query) return friends;
    return friends.filter(friend => [friend.name, friend.nickname, friend.email, friend.host]
      .filter(Boolean).some(value => String(value).toLocaleLowerCase().includes(query)));
  }, [friends, keyword]);
  const sortedJobs = useMemo(() => {
    const businessJobs = aiJobs.filter(job => !job.id.startsWith('external:'));
    // Model lifecycle events normally carry the same requestId as a business
    // job. Older/unscoped events do not; hide those generic cards when a real
    // task finished at the same time so one AI task remains one chat bubble.
    return aiJobs
      .filter(job => {
        if (!job.id.startsWith('external:')) return true;
        const time = safeDateMs(job.finishedAt || job.updatedAt || job.createdAt);
        return !businessJobs.some(task => Math.abs(safeDateMs(task.finishedAt || task.updatedAt || task.createdAt) - time) < 12_000);
      })
      .sort((a, b) => safeDateMs(b.updatedAt) - safeDateMs(a.updatedAt));
  }, [aiJobs]);
  const visibleMessages = useMemo(() => messages.filter(item => !hiddenChatIds.includes(item.id)), [hiddenChatIds, messages]);
  const selectedName = selectedFriend?.name || selectedFriend?.nickname || selectedFriend?.email || selectedFriend?.host || '';
  const activeSystemReplies = useMemo(() => replies.filter(reply => reply.messageId === 'system-reply'), [replies]);

  useEffect(() => {
    if (!messageStateLoaded) return;
    const checkNotes = () => {
      const now = Date.now();
      let changed = false;
      const nextNotes = notes.map(note => {
        if (note.completed || !note.dueAt) return note;
        const due = safeDateMs(note.dueAt);
        if (!due) return note;
        const stage: 'due-soon' | 'overdue' | null = due <= now ? 'overdue' : due - now <= NOTE_DUE_SOON_MS ? 'due-soon' : null;
        if (!stage || note.notified?.includes(stage)) return note;
        changed = true;
        void window.electronAPI.showSystemNotification?.({
          title: stage === 'overdue' ? `便签已逾期：${note.title}` : `便签即将到期：${note.title}`,
          body: note.content || (stage === 'overdue' ? '请尽快处理该便签。' : '该便签将在 24 小时内到期。'),
          target: 'overview',
        });
        return { ...note, notified: [...(note.notified || []), stage] };
      });
      if (changed) {
        setNotes(nextNotes);
        persistMessageCenterState({ notes: nextNotes });
      }
    };
    checkNotes();
    const timer = window.setInterval(checkNotes, 60_000);
    return () => window.clearInterval(timer);
  // Persistence is intentionally performed only when a new notification stage is reached.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [messageStateLoaded, notes]);

  useEffect(() => {
    if (!open) return;
    messageEndRef.current?.scrollIntoView({ block: 'end' });
  }, [activeKey, loadingMessages, messages, open, activeSystemReplies.length, sortedJobs.length]);

  const selectFriend = (friend: CollaborationPeerInfo) => {
    setSelectionMode(false);
    setSelectedMessageIds(new Set());
    setActiveKey(`friend:${friend.id}`);
    onSelectFriend(friend);
  };
  const markSystemRead = (ids = systemMessages.map(item => item.id)) => {
    const next = [...new Set([...readIds, ...ids])].slice(-1000);
    setReadIds(next);
    persistMessageCenterState({ readIds: next });
  };
  const openSystemConversation = () => {
    setSelectionMode(false);
    setSelectedMessageIds(new Set());
    setActiveKey('system');
    markSystemRead();
  };
  useEffect(() => {
    if (!messageStateLoaded || !open || activeKey !== 'system') return;
    const unreadIds = systemMessages.filter(item => !readIds.includes(item.id)).map(item => item.id);
    if (!unreadIds.length) return;
    const next = [...new Set([...readIds, ...unreadIds])].slice(-1000);
    setReadIds(next);
    persistMessageCenterState({ readIds: next });
  // Marking only runs when opening the system conversation or when a new system message arrives.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [messageStateLoaded, open, activeKey, systemMessages.map(item => item.id).join('|')]);
  const dismissSystem = (id: string) => {
    const next = [...new Set([...dismissedIds, id])].slice(-400);
    setDismissedIds(next);
    persistMessageCenterState({ dismissedIds: next });
  };
  const replyToSystem = () => {
    const content = systemDraft.trim();
    if (!content) return;
    const reply: LocalReply = { id: `reply-${Date.now()}`, messageId: 'system-reply', content, createdAt: new Date().toISOString() };
    const next = [...replies, reply].slice(-300);
    setReplies(next);
    persistMessageCenterState({ replies: next });
    setSystemDraft('');
  };

  const avatarName = (name: string) => name.trim().slice(0, 1).toLocaleUpperCase() || 'P';
  const currentFriendConversation = activeKey.startsWith('friend:');
  const activeFriend = currentFriendConversation ? selectedFriend : null;

  const openNoteEditor = (source?: MessageReference, existing?: MessageNote) => {
    setEditingNoteId(existing?.id || '');
    setNoteTitle(existing?.title || source?.title || '消息待办');
    setNoteContent(existing?.content || source?.content || '');
    setNoteDueAt(existing?.dueAt ? existing.dueAt.slice(0, 16) : '');
    setNoteSourceMessageId(existing?.sourceMessageId || source?.id || '');
    setNoteEditorOpen(true);
  };

  const saveNote = () => {
    const title = noteTitle.trim();
    if (!title) {
      message.warning('请填写便签标题');
      return;
    }
    const now = new Date().toISOString();
    const dueAt = noteDueAt ? new Date(noteDueAt).toISOString() : undefined;
    const nextNotes = editingNoteId
      ? notes.map(note => note.id === editingNoteId ? { ...note, title, content: noteContent.trim(), dueAt, updatedAt: now, notified: [] } : note)
      : [{ id: `note-${Date.now()}-${Math.random().toString(16).slice(2, 7)}`, title, content: noteContent.trim(), dueAt, createdAt: now, updatedAt: now, sourceMessageId: noteSourceMessageId || undefined, notified: [] }, ...notes];
    setNotes(nextNotes);
    persistMessageCenterState({ notes: nextNotes });
    setNoteEditorOpen(false);
    message.success(editingNoteId ? '便签已更新' : '已添加到我的便签');
  };

  const updateNote = (id: string, updates: Partial<MessageNote>) => {
    const nextNotes = notes.map(note => note.id === id ? { ...note, ...updates, updatedAt: new Date().toISOString() } : note);
    setNotes(nextNotes);
    persistMessageCenterState({ notes: nextNotes });
  };

  const removeNote = (id: string) => {
    const nextNotes = notes.filter(note => note.id !== id);
    setNotes(nextNotes);
    persistMessageCenterState({ notes: nextNotes });
  };

  const systemReference = (item: SystemMessage): MessageReference => ({ id: item.id, kind: 'system', title: item.title, content: item.content, createdAt: item.createdAt, system: item });
  const aiReference = (job: AIJob): MessageReference => ({ id: job.id, kind: 'ai', title: job.title, content: job.error || job.resultPreview || `AI 任务状态：${aiStatusMeta[job.status].label}`, createdAt: job.finishedAt || job.startedAt || job.createdAt, aiJob: job });
  const chatReference = (item: CollaborationChatMessage): MessageReference => ({ id: item.id, kind: 'friend', title: selectedName || '好友消息', content: item.content, createdAt: item.createdAt, chat: item });

  const referencesForActiveConversation = () => activeKey === 'system'
    ? systemMessages.map(systemReference)
    : activeKey === 'ai'
      ? sortedJobs.map(aiReference)
      : currentFriendConversation
        ? visibleMessages.map(chatReference)
        : [];

  const toggleMessageSelection = (id: string) => {
    setSelectedMessageIds(previous => {
      const next = new Set(previous);
      if (next.has(id)) next.delete(id); else next.add(id);
      return next;
    });
  };

  const enterSelectionMode = (item: MessageReference) => {
    setSelectionMode(true);
    setSelectedMessageIds(new Set([item.id]));
  };

  const deleteReferences = (items: MessageReference[]) => {
    const systemIds = items.filter(item => item.kind === 'system').map(item => item.id);
    const aiItems = items.filter(item => item.kind === 'ai');
    const chatIds = items.filter(item => item.kind === 'friend').map(item => item.id);
    if (systemIds.length) {
      const next = [...new Set([...dismissedIds, ...systemIds])].slice(-400);
      setDismissedIds(next);
      persistMessageCenterState({ dismissedIds: next });
    }
    aiItems.forEach(item => {
      const job = item.aiJob;
      if (!job) return;
      if (job.status === 'queued' || job.status === 'running') cancelJob(job.id);
      clearJob(job.id);
    });
    if (chatIds.length) {
      const next = [...new Set([...hiddenChatIds, ...chatIds])].slice(-3000);
      setHiddenChatIds(next);
      persistMessageCenterState({ hiddenChatIds: next });
    }
    setSelectionMode(false);
    setSelectedMessageIds(new Set());
  };

  const replyToMessage = (item: MessageReference) => {
    if (item.kind === 'friend') onDraftChange(`回复“${item.content.slice(0, 48)}”：`);
    else if (item.kind === 'system') setSystemDraft(`回复“${item.title}”：`);
    else message.info('AI 任务消息不可直接回复，可添加到便签继续跟进');
  };

  const viewMessage = (item: MessageReference) => {
    if (selectionMode) {
      toggleMessageSelection(item.id);
      return;
    }
    if (item.kind === 'system' && item.system) {
      markSystemRead([item.id]);
      if (item.system.noteId) {
        setActiveKey('notes');
        return;
      }
      onOpenSystemTarget(item.system.target, item.system.projectId);
      onClose();
      return;
    }
    if (item.kind === 'ai' && item.aiJob) {
      const target: NotificationTarget = item.aiJob.scene === 'report' ? 'project-report' : item.aiJob.scene === 'review' ? 'project-review' : item.aiJob.projectId ? 'project-plan' : 'overview';
      onOpenSystemTarget(target, item.aiJob.projectId);
      onClose();
    }
  };

  const openForward = (items: MessageReference[]) => {
    if (!friends.some(friend => friend.online)) {
      message.warning('暂无在线好友可转发');
      return;
    }
    setForwardItems(items);
    setForwardFriendIds([]);
  };

  const confirmForward = async () => {
    if (!forwardItems.length || !forwardFriendIds.length) return;
    setForwarding(true);
    let sent = 0;
    try {
      for (const friendId of forwardFriendIds) {
        for (const item of forwardItems) {
          const result = await window.electronAPI.sendCollaborationChatMessage?.({ friendId, content: `[转发] ${item.title}\n${item.content}`.slice(0, 4000) });
          if (result?.success) sent += 1;
        }
      }
      message.success(`已转发 ${sent} 条消息`);
      setForwardItems([]);
      setForwardFriendIds([]);
      setSelectionMode(false);
      setSelectedMessageIds(new Set());
      if (activeFriend) onSelectFriend(activeFriend);
    } finally {
      setForwarding(false);
    }
  };

  const menuItemsFor = (item: MessageReference): NonNullable<React.ComponentProps<typeof Dropdown>['menu']>['items'] => {
    const aiActions = item.aiJob
      ? [
        ...((item.aiJob.status === 'queued' || item.aiJob.status === 'running')
          ? [{ key: 'cancel-ai', danger: true, label: '取消任务', onClick: () => cancelJob(item.aiJob!.id) }]
          : []),
        ...(item.aiJob.status === 'failed' && item.aiJob.canRetry
          ? [{ key: 'retry-ai', label: '重试任务', onClick: () => void retryJob(item.aiJob!.id) }]
          : []),
      ]
      : [];
    return [
      ...aiActions,
      ...(aiActions.length ? [{ type: 'divider' as const }] : []),
      { key: 'forward', icon: <ShareAltOutlined />, label: '转发', onClick: () => openForward([item]) },
      { key: 'select', icon: <CheckOutlined />, label: '多选', onClick: () => enterSelectionMode(item) },
      { key: 'reply', icon: <MessageOutlined />, label: '回复', onClick: () => replyToMessage(item) },
      { key: 'note', icon: <SnippetsOutlined />, label: '添加待办（便签）', onClick: () => openNoteEditor(item) },
      { type: 'divider' },
      { key: 'delete', danger: true, icon: <DeleteOutlined />, label: '删除', onClick: () => deleteReferences([item]) },
    ];
  };

  const selectedReferences = referencesForActiveConversation().filter(item => selectedMessageIds.has(item.id));

  const respondToTaskOffer = async (offerId: string, status: 'accepted' | 'rejected', projectId?: string) => {
    if (!activeFriend) return;
    setRespondingTaskOffer(true);
    const result = await window.electronAPI.respondCollaborationTaskOffer?.({ friendId: activeFriend.id, offerId, status, projectId });
    setRespondingTaskOffer(false);
    if (!result?.success) {
      message.error(result?.error || '任务邀约处理失败');
      return;
    }
    if (status === 'accepted') {
      await loadTasks();
      message.success('任务已加入所选项目的计划列表');
      setAcceptingTaskOfferId('');
      setAcceptProjectId('');
    }
    onSelectFriend(activeFriend);
  };

  const openAcceptTaskOffer = (offerId: string) => {
    if (projects.length === 0) {
      message.warning('请先创建或导入一个本地项目，再接受协作任务');
      return;
    }
    setAcceptingTaskOfferId(offerId);
    setAcceptProjectId(currentProjectId && projects.some(project => project.id === currentProjectId) ? currentProjectId : projects[0].id);
  };

  return (
    <Modal title={null} open={open} onCancel={onClose} footer={null} width="min(1480px, calc(100vw - 56px))" style={{ top: 26 }} styles={{ body: { padding: 0 } }} destroyOnClose={false} className="message-center-modal">
      <div className="message-center-shell">
        <aside className="message-center-sidebar">
          <div className="message-center-sidebar-head">
            <div className="message-center-brand">
              <Avatar size={36} icon={<MessageOutlined />} />
              <div><Text strong>消息中心</Text><Text type="secondary">系统 · AI · 好友</Text></div>
            </div>
            <Space size={0}>
              <Tooltip title="刷新好友状态"><Button type="text" icon={<ReloadOutlined />} onClick={onRefresh} /></Tooltip>
              <Badge count={pendingRequestCount} size="small" offset={[-1, 2]}><Tooltip title="添加好友"><Button type="text" icon={<PlusOutlined />} onClick={onOpenAddFriend} /></Tooltip></Badge>
            </Space>
          </div>
          <Input value={keyword} onChange={event => setKeyword(event.target.value)} prefix={<SearchOutlined />} placeholder="搜索好友" allowClear />
          <div className="message-center-conversations">
            <button className={`message-center-conversation message-center-system-conversation ${activeKey === 'system' ? 'is-active' : ''}`} onClick={openSystemConversation}>
              <Avatar className="message-center-conversation-avatar" icon={<BellOutlined />} />
              <span className="message-center-conversation-copy"><b>系统消息</b><small>{systemMessages[0]?.title || '项目状态与提醒'}</small></span>
              {unreadSystemMessages.length > 0 && <span className="message-center-unread-badge"><Badge count={unreadSystemMessages.length} size="small" overflowCount={99} /></span>}
            </button>
            <button className={`message-center-conversation message-center-ai-conversation ${activeKey === 'ai' ? 'is-active' : ''}`} onClick={() => { setActiveKey('ai'); setSelectionMode(false); setSelectedMessageIds(new Set()); }}>
              <Avatar className="message-center-conversation-avatar" icon={<RobotOutlined />} />
              <span className="message-center-conversation-copy"><b>AI 任务</b><small>{aiJobs.some(job => job.status === 'running') ? '有任务正在执行' : '查看任务执行记录'}</small></span>
              {aiJobs.filter(job => job.status === 'running' || job.status === 'queued').length > 0 && <span className="message-center-ai-status"><Badge status="processing" /></span>}
            </button>
            <button className={`message-center-conversation message-center-notes-conversation ${activeKey === 'notes' ? 'is-active' : ''}`} onClick={() => { setActiveKey('notes'); setSelectionMode(false); setSelectedMessageIds(new Set()); }}>
              <Avatar className="message-center-conversation-avatar" icon={<SnippetsOutlined />} />
              <span className="message-center-conversation-copy"><b>我的便签</b><small>{notes.length ? `${notes.filter(note => !note.completed).length} 条未完成` : '集中管理提醒和待办'}</small></span>
              {notes.some(note => !note.completed && note.dueAt && safeDateMs(note.dueAt) <= Date.now()) && <span className="message-center-unread-badge"><Badge count="!" size="small" /></span>}
            </button>
            <div className="message-center-section-label">好友</div>
            {visibleFriends.length === 0 ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无好友" imageStyle={{ height: 34 }}><Button type="link" size="small" onClick={onOpenAddFriend}>添加好友</Button></Empty> : (
              <List split={false} dataSource={visibleFriends} renderItem={friend => {
                const name = friend.name || friend.nickname || friend.email || friend.host;
                const active = activeKey === `friend:${friend.id}`;
                return <List.Item className={`message-center-friend ${active ? 'is-active' : ''}`} onClick={() => selectFriend(friend)}>
                  <Badge dot color={friend.online ? '#52c41a' : '#bfbfbf'} offset={[-1, 28]}><Avatar src={friend.avatar}>{!friend.avatar && avatarName(name)}</Avatar></Badge>
                  <span><b>{name}</b><small>{friend.online ? '在线' : '离线'}{friend.email ? ` · ${friend.email}` : ''}</small></span>
                </List.Item>;
              }} />
            )}
          </div>
        </aside>

        <section className="message-center-chat">
          {activeKey === 'system' && <>
            <header className="message-center-chat-head"><Space><Avatar style={{ background: '#e6f4ff', color: '#1677ff' }} icon={<BellOutlined />} /><div><Text strong>系统消息</Text><Text type="secondary">项目报告、审查与截止提醒</Text></div></Space><Button size="small" onClick={() => { if (!dismissedIds.length) return; setDismissedIds([]); persistMessageCenterState({ dismissedIds: [] }); }}>恢复已删除</Button></header>
            <div className="message-center-thread">
              {systemMessages.length === 0 ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无系统消息" style={{ marginTop: 110 }} /> : systemMessages.map(item => {
                const reference = systemReference(item);
                return <InteractiveMessage key={item.id} menuItems={menuItemsFor(reference)} onClick={() => viewMessage(reference)}>
                  <div className={`message-bubble-row ${selectedMessageIds.has(item.id) ? 'is-selected' : ''}`}>
                    <div className="message-selection-avatar">
                      <Avatar size={30} style={{ background: item.severity === 'high' ? '#fff1f0' : item.severity === 'medium' ? '#fff7e6' : '#e6f4ff', color: item.severity === 'high' ? '#ff4d4f' : item.severity === 'medium' ? '#fa8c16' : '#1677ff' }} icon={<BellOutlined />} />
                      {selectionMode && <Checkbox checked={selectedMessageIds.has(item.id)} onClick={event => event.stopPropagation()} onChange={() => toggleMessageSelection(item.id)} />}
                    </div>
                    <div className="message-bubble message-bubble-system"><Space size={6}><Text strong>{item.title}</Text><Tag color={item.severity === 'high' ? 'red' : item.severity === 'medium' ? 'gold' : 'blue'}>{item.category}</Tag></Space><Text>{item.content}</Text><div className="message-bubble-meta"><span>{formatTime(item.createdAt)}</span><span>单击查看</span></div></div>
                  </div>
                </InteractiveMessage>;
              })}
              {activeSystemReplies.map(reply => <div className="message-bubble-row is-outgoing" key={reply.id}><div className="message-bubble message-bubble-outgoing"><Text>{reply.content}</Text><span className="message-bubble-meta">{formatTime(reply.createdAt)}</span></div></div>)}
              <div ref={messageEndRef} />
            </div>
            <footer className="message-center-composer"><Input.TextArea value={systemDraft} onChange={event => setSystemDraft(event.target.value)} onPressEnter={event => { if (!event.shiftKey) { event.preventDefault(); replyToSystem(); } }} placeholder="回复或记录处理备注（仅保存到本机）" autoSize={{ minRows: 2, maxRows: 4 }} /><div><Text type="secondary">Enter 发送，Shift + Enter 换行</Text><Button type="primary" icon={<SendOutlined />} disabled={!systemDraft.trim()} onClick={replyToSystem}>回复</Button></div></footer>
          </>}

          {activeKey === 'ai' && <>
            <header className="message-center-chat-head"><Space><Avatar style={{ background: '#f3e8ff', color: '#7c3aed' }} icon={<RobotOutlined />} /><div><Text strong>AI 任务</Text><Text type="secondary">任务进度、结果和失败原因</Text></div></Space></header>
            <div className="message-center-thread">{sortedJobs.length === 0 ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无 AI 任务" style={{ marginTop: 110 }} /> : sortedJobs.map(job => {
              const meta = aiStatusMeta[job.status]; const active = job.status === 'queued' || job.status === 'running';
              const statusTitle = job.status === 'completed' ? '任务完成' : job.status === 'failed' ? '任务失败' : job.status === 'cancelled' ? '任务已取消' : job.status === 'queued' ? '任务排队中' : '任务进行中';
              const detail = job.error || job.resultPreview || (active ? `当前进度 ${job.progress || 0}%` : '任务已结束');
              const reference = aiReference(job);
              return <InteractiveMessage key={job.id} menuItems={menuItemsFor(reference)} onClick={() => viewMessage(reference)}>
                <div className={`message-bubble-row ${selectedMessageIds.has(job.id) ? 'is-selected' : ''}`}>
                  <div className="message-selection-avatar">
                    <Avatar size={30} style={{ background: '#f3e8ff', color: '#7c3aed' }} icon={<RobotOutlined />} />
                    {selectionMode && <Checkbox checked={selectedMessageIds.has(job.id)} onClick={event => event.stopPropagation()} onChange={() => toggleMessageSelection(job.id)} />}
                  </div>
                  <div className={`message-bubble message-bubble-system message-bubble-ai ${job.status === 'failed' ? 'is-failed' : ''}`}><Space size={6}><Text strong>{statusTitle}</Text><Tag color={meta.color}>{meta.label}</Tag></Space><Text type="secondary" className="message-ai-task-title">{job.title}</Text><Text className="message-ai-task-detail">{detail}</Text>{active && <div className="message-progress"><span style={{ width: `${job.progress || 0}%` }} /></div>}<div className="message-bubble-meta"><span>{formatTime(job.finishedAt || job.startedAt || job.createdAt)}</span><span>单击查看</span></div></div>
                </div>
              </InteractiveMessage>;
            })}<div ref={messageEndRef} /></div>
          </>}

          {activeKey === 'notes' && <>
            <header className="message-center-chat-head">
              <Space><Avatar style={{ background: '#fff7e6', color: '#fa8c16' }} icon={<SnippetsOutlined />} /><div><Text strong>我的便签</Text><Text type="secondary">轻量提醒，不会加入项目任务或工作流</Text></div></Space>
              <Button type="primary" icon={<PlusOutlined />} onClick={() => openNoteEditor()}>新建便签</Button>
            </header>
            <div className="message-center-thread message-note-list">
              {notes.length === 0 ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无便签，可从任意消息的快捷菜单添加" style={{ marginTop: 110 }} /> : notes
                .slice()
                .sort((a, b) => Number(Boolean(a.completed)) - Number(Boolean(b.completed)) || safeDateMs(a.dueAt || a.createdAt) - safeDateMs(b.dueAt || b.createdAt))
                .map(note => {
                  const dueMs = note.dueAt ? safeDateMs(note.dueAt) : 0;
                  const overdue = !note.completed && dueMs > 0 && dueMs <= Date.now();
                  const dueSoon = !note.completed && dueMs > Date.now() && dueMs - Date.now() <= NOTE_DUE_SOON_MS;
                  return <div className={`message-note-card ${note.completed ? 'is-completed' : ''} ${overdue ? 'is-overdue' : dueSoon ? 'is-due-soon' : ''}`} key={note.id}>
                    <Checkbox checked={Boolean(note.completed)} onChange={event => updateNote(note.id, { completed: event.target.checked })} />
                    <div className="message-note-copy">
                      <Space size={6} wrap><Text strong delete={Boolean(note.completed)}>{note.title}</Text>{overdue && <Tag color="red">已逾期</Tag>}{dueSoon && <Tag color="gold">即将到期</Tag>}{note.completed && <Tag color="green">已完成</Tag>}</Space>
                      {note.content && <Text type="secondary">{note.content}</Text>}
                      <span>{note.dueAt ? `提醒时间：${new Date(note.dueAt).toLocaleString('zh-CN')}` : '未设置提醒时间'}</span>
                    </div>
                    <Space size={2}>
                      <Button type="text" size="small" onClick={() => openNoteEditor(undefined, note)}>编辑</Button>
                      <Popconfirm title="删除这条便签？" onConfirm={() => removeNote(note.id)}><Button type="text" danger size="small" icon={<DeleteOutlined />} /></Popconfirm>
                    </Space>
                  </div>;
                })}
            </div>
          </>}

          {currentFriendConversation && activeFriend && <>
            <header className="message-center-chat-head"><Space><Badge dot color={activeFriend.online ? '#52c41a' : '#bfbfbf'} offset={[-1, 29]}><Avatar src={activeFriend.avatar}>{!activeFriend.avatar && avatarName(selectedName)}</Avatar></Badge><div><Text strong>{selectedName}</Text><Text type="secondary">{activeFriend.online ? '在线，可发送消息和文件' : '离线，暂不能发送'}</Text></div></Space><Space size={2}><Tooltip title="发送当前项目进度"><Button type="text" icon={<FolderOpenOutlined />} onClick={onShareProject} /></Tooltip><Tooltip title="发送文件"><Button type="text" icon={<PaperClipOutlined />} loading={sendingFile} disabled={!activeFriend.online} onClick={onSendFile} /></Tooltip><Tooltip title="发送文件夹"><Button type="text" icon={<FolderOutlined />} loading={sendingFile} disabled={!activeFriend.online} onClick={onSendFolder} /></Tooltip><Popconfirm title="移除这位好友？" onConfirm={() => onRemoveFriend(activeFriend.id)}><Button type="text" danger icon={<UserDeleteOutlined />} /></Popconfirm></Space></header>
            <div className="message-center-thread">{loadingMessages ? <div className="message-loading">正在加载聊天记录…</div> : visibleMessages.length === 0 ? <Empty image={Empty.PRESENTED_IMAGE_SIMPLE} description="暂无消息，发一句问候吧" style={{ marginTop: 110 }} /> : visibleMessages.map(item => {
              const reference = chatReference(item);
              const selected = selectedMessageIds.has(item.id);
              const avatar = <div className="message-selection-avatar">
                <Avatar size={30} src={item.direction === 'incoming' ? activeFriend.avatar : undefined}>{item.direction === 'incoming' ? (!activeFriend.avatar && avatarName(selectedName)) : '我'}</Avatar>
                {selectionMode && <Checkbox checked={selected} onClick={event => event.stopPropagation()} onChange={() => toggleMessageSelection(item.id)} />}
              </div>;
              return <InteractiveMessage key={item.id} menuItems={menuItemsFor(reference)} onClick={() => viewMessage(reference)}>
                <div className={`message-bubble-row ${item.direction === 'outgoing' ? 'is-outgoing' : ''} ${selected ? 'is-selected' : ''}`}>
                  {item.direction === 'incoming' && avatar}
                  <div className={`message-bubble ${item.direction === 'outgoing' ? 'message-bubble-outgoing' : ''}`}>
                    <Text>{item.content}</Text>
                    {item.taskOffer && <div className="message-task-offer"><Space wrap size={5}><Tag color={item.taskOffer.status === 'accepted' ? 'green' : item.taskOffer.status === 'rejected' ? 'red' : 'blue'}>{item.taskOffer.status === 'accepted' ? '已接受' : item.taskOffer.status === 'rejected' ? '已拒绝' : '待响应'}</Tag>{item.taskOffer.projectName && <Tag>{item.taskOffer.projectName}</Tag>}{item.taskOffer.stageName && <Tag color="purple">{item.taskOffer.stageName}</Tag>}</Space><Text strong>{item.taskOffer.title}</Text>{item.taskOffer.sectionTitle && <Text type="secondary">审查定位：{item.taskOffer.sectionTitle}</Text>}{item.taskOffer.description && <Text type="secondary">{item.taskOffer.description}</Text>}{item.taskOffer.attachmentName && <Text type="secondary"><PaperClipOutlined /> 附带文件：{item.taskOffer.attachmentName}</Text>}{item.direction === 'incoming' && item.taskOffer.status === 'pending' && <Space size={6}><Button size="small" type="primary" onClick={event => { event.stopPropagation(); openAcceptTaskOffer(item.taskOffer!.id); }}>接受任务</Button><Button size="small" danger loading={respondingTaskOffer} onClick={event => { event.stopPropagation(); void respondToTaskOffer(item.taskOffer!.id, 'rejected'); }}>拒绝</Button></Space>}</div>}
                    <span className="message-bubble-meta">{formatTime(item.createdAt)}</span>
                  </div>
                  {item.direction === 'outgoing' && avatar}
                </div>
              </InteractiveMessage>;
            })}<div ref={messageEndRef} /></div>
            <footer className="message-center-composer"><Input.TextArea value={draft} onChange={event => onDraftChange(event.target.value)} onPressEnter={event => { if (!event.shiftKey) { event.preventDefault(); onSendMessage(); } }} placeholder={activeFriend.online ? '输入消息，Enter 发送' : '好友离线，暂不能发送'} autoSize={{ minRows: 2, maxRows: 4 }} disabled={!activeFriend.online || sending} /><div><Space><Tooltip title="发送文件"><Button type="text" icon={<PaperClipOutlined />} disabled={!activeFriend.online} onClick={onSendFile} /></Tooltip><Tooltip title="发送文件夹"><Button type="text" icon={<FolderOutlined />} disabled={!activeFriend.online} onClick={onSendFolder} /></Tooltip><Tooltip title="分享当前项目"><Button type="text" icon={<FileOutlined />} onClick={onShareProject} /></Tooltip></Space><Button type="primary" icon={<SendOutlined />} loading={sending} disabled={!draft.trim() || !activeFriend.online} onClick={onSendMessage}>发送</Button></div></footer>
          </>}
          {selectionMode && <div className="message-selection-toolbar">
            <Text strong>已选 {selectedReferences.length} 条</Text>
            <Tooltip title="删除"><Button shape="circle" danger icon={<DeleteOutlined />} disabled={!selectedReferences.length} onClick={() => deleteReferences(selectedReferences)} /></Tooltip>
            <Tooltip title="转发"><Button shape="circle" type="primary" icon={<ShareAltOutlined />} disabled={!selectedReferences.length} onClick={() => openForward(selectedReferences)} /></Tooltip>
            <Tooltip title="退出多选"><Button shape="circle" icon={<CloseOutlined />} onClick={() => { setSelectionMode(false); setSelectedMessageIds(new Set()); }} /></Tooltip>
          </div>}
        </section>
      </div>
      <Modal
        open={forwardItems.length > 0}
        title={`转发 ${forwardItems.length} 条消息`}
        okText="转发"
        cancelText="取消"
        confirmLoading={forwarding}
        okButtonProps={{ disabled: forwardFriendIds.length === 0 }}
        onCancel={() => { if (!forwarding) { setForwardItems([]); setForwardFriendIds([]); } }}
        onOk={() => void confirmForward()}
      >
        <Text type="secondary" style={{ display: 'block', marginBottom: 12 }}>可同时选择多位在线好友。转发内容会标注原消息标题。</Text>
        <Select
          mode="multiple"
          value={forwardFriendIds}
          style={{ width: '100%' }}
          placeholder="选择在线好友"
          onChange={setForwardFriendIds}
          options={friends.filter(friend => friend.online).map(friend => ({ value: friend.id, label: friend.name || friend.nickname || friend.email || friend.host }))}
        />
      </Modal>
      <Modal
        open={noteEditorOpen}
        title={editingNoteId ? '编辑便签' : '添加待办便签'}
        okText="保存"
        cancelText="取消"
        onCancel={() => setNoteEditorOpen(false)}
        onOk={saveNote}
      >
        <Space direction="vertical" size={12} style={{ width: '100%' }}>
          <div><Text strong>标题</Text><Input value={noteTitle} maxLength={100} placeholder="需要提醒的事项" onChange={event => setNoteTitle(event.target.value)} /></div>
          <div><Text strong>备注</Text><Input.TextArea value={noteContent} maxLength={1000} autoSize={{ minRows: 3, maxRows: 7 }} placeholder="可补充上下文或处理说明" onChange={event => setNoteContent(event.target.value)} /></div>
          <div><Text strong>提醒时间（可选）</Text><Input type="datetime-local" value={noteDueAt} onChange={event => setNoteDueAt(event.target.value)} /></div>
          <Text type="secondary">便签只用于个人提醒，不会创建项目任务。到期前 24 小时及逾期后会在消息中心提醒。</Text>
        </Space>
      </Modal>
      <Modal
        open={Boolean(acceptingTaskOfferId)}
        title="选择任务归属项目"
        okText="接受并加入计划"
        cancelText="取消"
        confirmLoading={respondingTaskOffer}
        onCancel={() => { if (!respondingTaskOffer) { setAcceptingTaskOfferId(''); setAcceptProjectId(''); } }}
        onOk={() => void respondToTaskOffer(acceptingTaskOfferId, 'accepted', acceptProjectId)}
        okButtonProps={{ disabled: !acceptProjectId }}
      >
        <Text type="secondary" style={{ display: 'block', marginBottom: 10 }}>外部项目ID不会直接写入本地数据，请选择这项协作任务要加入的本地项目。</Text>
        <Select
          value={acceptProjectId || undefined}
          style={{ width: '100%' }}
          placeholder="选择本地项目"
          onChange={setAcceptProjectId}
          options={projects.map(project => ({ value: project.id, label: project.name }))}
        />
      </Modal>
    </Modal>
  );
};

export default FriendChatWorkspace;
